name: compiler

on: 
  push:
    tags:
      - compiler.**

jobs:
  publish_compiler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          sparse-checkout: packages/compiler
          token: ${{ secrets.TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install
        working-directory: ./packages/compiler
        run: | 
         npm install
         npm run build
         npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
